name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
          # server-id: 'private'
          # settings-path: ${{ github.workspace }}

      - uses: s4u/maven-settings-action@v3.1.0
        with:
          servers: |
            [ { "id": "private", "username": "${{ github.actor }}", "password": "${{ github.token }}" } ]

      - name: Build with Maven
        run: |
          echo ACTOR: ${{ github.actor }}
          echo TOKEN: ${{ github.token }}
          echo w00t
          cat /home/runner/.m2/settings.xml
          echo bl44t
          mvn --no-transfer-progress --update-snapshots -Djansi.force=true -Dstyle.color=always clean package
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
