name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: read-all

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
          # server-id: 'private'
          # server-password: PRIVATE_TOKEN
          # settings-path: ${{ github.workspace }}

      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: 1069430
          private-key: ${{ secrets.JAYBAWS_CI_PKEY }}
          owner: ${{ github.repository_owner }}

      - uses: s4u/maven-settings-action@v3.1.0
        with:
          githubServer: false
          servers: |
            [{ "id": "github", "username": "${{ github.actor }}", "password": "${{ secrets.THE_TOKEN }}" }, { "id": "private", "username": "${{ github.actor }}", "password": "${{ steps.generate-token.outputs.token }}" }]

      - name: Build with Maven
        run: |
          cat /home/runner/.m2/settings.xml
          echo -n '${{ steps.generate-token.outputs.token }}' | base64
          mvn -s /home/runner/.m2/settings.xml --no-transfer-progress --update-snapshots -Djansi.force=true -Dstyle.color=always clean package
        # env:
        #   PRIVATE_TOKEN: ${{ steps.generate-token.outputs.token }}
 