name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - uses: s4u/maven-settings-action@v3.1.0
        with:
          githubServer: false
          servers: |
            [{ "id": "github", "username": "${{ github.actor }}", "password": "${{ secrets.THE_TOKEN }}" }, { "id": "private", "username": "${{ github.actor }}", "password": "${{ secrets.THE_TOKEN }}" }]

      - name: Build with Maven
        run: |
          mvn --no-transfer-progress --update-snapshots -Djansi.force=true -Dstyle.color=always clean deploy
